import './e2e/ws-rpc-client-tests'
import './e2e/client-tests'
import './e2e/contract-tests'
import './e2e/evm-contract-tests'
import './e2e/loom-provider-web3-tests'
import './e2e/loom-provider-tests'
import './e2e/loom-provider-eth-get-logs'
