/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  EthereumGatewayV2,
  EthereumGatewayV2Interface,
} from "../EthereumGatewayV2";

const _abi = [
  {
    constant: true,
    inputs: [],
    name: "vmc",
    outputs: [
      {
        name: "",
        type: "address",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "getAllowAnyToken",
    outputs: [
      {
        name: "",
        type: "bool",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "loomAddress",
    outputs: [
      {
        name: "",
        type: "address",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      {
        name: "amount",
        type: "uint256",
      },
      {
        name: "contractAddress",
        type: "address",
      },
    ],
    name: "depositERC20",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      {
        name: "enable",
        type: "bool",
      },
    ],
    name: "enableGateway",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: true,
    inputs: [
      {
        name: "contractAddress",
        type: "address",
      },
    ],
    name: "getERC20",
    outputs: [
      {
        name: "",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [
      {
        name: "",
        type: "address",
      },
    ],
    name: "nonces",
    outputs: [
      {
        name: "",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "getOwner",
    outputs: [
      {
        name: "",
        type: "address",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "owner",
    outputs: [
      {
        name: "",
        type: "address",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      {
        name: "amount",
        type: "uint256",
      },
      {
        name: "contractAddress",
        type: "address",
      },
      {
        name: "_signersIndexes",
        type: "uint256[]",
      },
      {
        name: "_v",
        type: "uint8[]",
      },
      {
        name: "_r",
        type: "bytes32[]",
      },
      {
        name: "_s",
        type: "bytes32[]",
      },
    ],
    name: "withdrawERC20",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      {
        name: "tokenAddress",
        type: "address",
      },
      {
        name: "allow",
        type: "bool",
      },
    ],
    name: "toggleAllowToken",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "getGatewayEnabled",
    outputs: [
      {
        name: "",
        type: "bool",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      {
        name: "allow",
        type: "bool",
      },
    ],
    name: "toggleAllowAnyToken",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: true,
    inputs: [
      {
        name: "",
        type: "address",
      },
    ],
    name: "allowedTokens",
    outputs: [
      {
        name: "",
        type: "bool",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [
      {
        name: "tokenAddress",
        type: "address",
      },
    ],
    name: "isTokenAllowed",
    outputs: [
      {
        name: "",
        type: "bool",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        name: "_vmc",
        type: "address",
      },
    ],
    payable: false,
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    payable: true,
    stateMutability: "payable",
    type: "fallback",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        name: "from",
        type: "address",
      },
      {
        indexed: false,
        name: "amount",
        type: "uint256",
      },
    ],
    name: "ETHReceived",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        name: "operator",
        type: "address",
      },
      {
        indexed: false,
        name: "from",
        type: "address",
      },
      {
        indexed: false,
        name: "tokenId",
        type: "uint256",
      },
      {
        indexed: false,
        name: "contractAddress",
        type: "address",
      },
      {
        indexed: false,
        name: "data",
        type: "bytes",
      },
    ],
    name: "ERC721Received",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        name: "operator",
        type: "address",
      },
      {
        indexed: false,
        name: "from",
        type: "address",
      },
      {
        indexed: false,
        name: "tokenId",
        type: "uint256",
      },
      {
        indexed: false,
        name: "amount",
        type: "uint256",
      },
      {
        indexed: false,
        name: "contractAddress",
        type: "address",
      },
      {
        indexed: false,
        name: "data",
        type: "bytes",
      },
    ],
    name: "ERC721XReceived",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        name: "operator",
        type: "address",
      },
      {
        indexed: false,
        name: "to",
        type: "address",
      },
      {
        indexed: false,
        name: "tokenTypes",
        type: "uint256[]",
      },
      {
        indexed: false,
        name: "amounts",
        type: "uint256[]",
      },
      {
        indexed: false,
        name: "contractAddress",
        type: "address",
      },
      {
        indexed: false,
        name: "data",
        type: "bytes",
      },
    ],
    name: "ERC721XBatchReceived",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        name: "owner",
        type: "address",
      },
      {
        indexed: false,
        name: "kind",
        type: "uint8",
      },
      {
        indexed: false,
        name: "contractAddress",
        type: "address",
      },
      {
        indexed: false,
        name: "value",
        type: "uint256",
      },
    ],
    name: "TokenWithdrawn",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        name: "from",
        type: "address",
      },
      {
        indexed: false,
        name: "amount",
        type: "uint256",
      },
      {
        indexed: false,
        name: "loomCoinAddress",
        type: "address",
      },
    ],
    name: "LoomCoinReceived",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        name: "from",
        type: "address",
      },
      {
        indexed: false,
        name: "amount",
        type: "uint256",
      },
      {
        indexed: false,
        name: "contractAddress",
        type: "address",
      },
    ],
    name: "ERC20Received",
    type: "event",
  },
  {
    constant: false,
    inputs: [
      {
        name: "tokenId",
        type: "uint256",
      },
      {
        name: "amount",
        type: "uint256",
      },
      {
        name: "contractAddress",
        type: "address",
      },
      {
        name: "_signersIndexes",
        type: "uint256[]",
      },
      {
        name: "_v",
        type: "uint8[]",
      },
      {
        name: "_r",
        type: "bytes32[]",
      },
      {
        name: "_s",
        type: "bytes32[]",
      },
    ],
    name: "withdrawERC721X",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      {
        name: "uid",
        type: "uint256",
      },
      {
        name: "contractAddress",
        type: "address",
      },
      {
        name: "_signersIndexes",
        type: "uint256[]",
      },
      {
        name: "_v",
        type: "uint8[]",
      },
      {
        name: "_r",
        type: "bytes32[]",
      },
      {
        name: "_s",
        type: "bytes32[]",
      },
    ],
    name: "withdrawERC721",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      {
        name: "amount",
        type: "uint256",
      },
      {
        name: "_signersIndexes",
        type: "uint256[]",
      },
      {
        name: "_v",
        type: "uint8[]",
      },
      {
        name: "_r",
        type: "bytes32[]",
      },
      {
        name: "_s",
        type: "bytes32[]",
      },
    ],
    name: "withdrawETH",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      {
        name: "_operator",
        type: "address",
      },
      {
        name: "_from",
        type: "address",
      },
      {
        name: "_tokenId",
        type: "uint256",
      },
      {
        name: "_amount",
        type: "uint256",
      },
      {
        name: "_data",
        type: "bytes",
      },
    ],
    name: "onERC721XReceived",
    outputs: [
      {
        name: "",
        type: "bytes4",
      },
    ],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      {
        name: "_operator",
        type: "address",
      },
      {
        name: "_from",
        type: "address",
      },
      {
        name: "_types",
        type: "uint256[]",
      },
      {
        name: "_amounts",
        type: "uint256[]",
      },
      {
        name: "_data",
        type: "bytes",
      },
    ],
    name: "onERC721XBatchReceived",
    outputs: [
      {
        name: "",
        type: "bytes4",
      },
    ],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      {
        name: "_operator",
        type: "address",
      },
      {
        name: "_from",
        type: "address",
      },
      {
        name: "_uid",
        type: "uint256",
      },
      {
        name: "_data",
        type: "bytes",
      },
    ],
    name: "onERC721Received",
    outputs: [
      {
        name: "",
        type: "bytes4",
      },
    ],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "getETH",
    outputs: [
      {
        name: "",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [
      {
        name: "uid",
        type: "uint256",
      },
      {
        name: "contractAddress",
        type: "address",
      },
    ],
    name: "getERC721",
    outputs: [
      {
        name: "",
        type: "bool",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [
      {
        name: "tokenId",
        type: "uint256",
      },
      {
        name: "contractAddress",
        type: "address",
      },
    ],
    name: "getERC721X",
    outputs: [
      {
        name: "",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
] as const;

export class EthereumGatewayV2__factory {
  static readonly abi = _abi;
  static createInterface(): EthereumGatewayV2Interface {
    return new utils.Interface(_abi) as EthereumGatewayV2Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): EthereumGatewayV2 {
    return new Contract(address, _abi, signerOrProvider) as EthereumGatewayV2;
  }
}

export const abi = _abi;