/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { SimpleStore, SimpleStoreInterface } from "../SimpleStore";

const _abi = [
  {
    constant: false,
    inputs: [
      {
        name: "_value",
        type: "uint256",
      },
    ],
    name: "set",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "get",
    outputs: [
      {
        name: "",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        name: "_value",
        type: "uint256",
      },
    ],
    name: "NewValueSet",
    type: "event",
  },
] as const;

export class SimpleStore__factory {
  static readonly abi = _abi;
  static createInterface(): SimpleStoreInterface {
    return new utils.Interface(_abi) as SimpleStoreInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): SimpleStore {
    return new Contract(address, _abi, signerOrProvider) as SimpleStore;
  }
}
