/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SimpleStore } from "./SimpleStore";
export * as factories from "./factories";
export { SimpleStore__factory } from "./factories/SimpleStore__factory";
