/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, Signer } from "ethers";
import { Provider } from "ethers/providers";

import { SimpleStore } from "./SimpleStore";

export class SimpleStoreFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): SimpleStore {
    return new Contract(address, _abi, signerOrProvider) as SimpleStore;
  }
}

const _abi = [
  {
    constant: false,
    inputs: [
      {
        name: "_value",
        type: "uint256"
      }
    ],
    name: "set",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function"
  },
  {
    constant: true,
    inputs: [],
    name: "get",
    outputs: [
      {
        name: "",
        type: "uint256"
      }
    ],
    payable: false,
    stateMutability: "view",
    type: "function"
  },
  {
    inputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "constructor"
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        name: "_value",
        type: "uint256"
      }
    ],
    name: "NewValueSet",
    type: "event"
  }
];
