/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export interface SimpleStoreInterface extends utils.Interface {
  functions: {
    "set(uint256)": FunctionFragment;
    "get()": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "set" | "get"): FunctionFragment;

  encodeFunctionData(functionFragment: "set", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "get", values?: undefined): string;

  decodeFunctionResult(functionFragment: "set", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "get", data: BytesLike): Result;

  events: {
    "NewValueSet(uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "NewValueSet"): EventFragment;
}

export interface NewValueSetEventObject {
  _value: BigNumber;
}
export type NewValueSetEvent = TypedEvent<[BigNumber], NewValueSetEventObject>;

export type NewValueSetEventFilter = TypedEventFilter<NewValueSetEvent>;

export interface SimpleStore extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: SimpleStoreInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    set(
      _value: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    get(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  set(
    _value: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  get(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    set(_value: BigNumberish, overrides?: CallOverrides): Promise<void>;

    get(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {
    "NewValueSet(uint256)"(
      _value?: BigNumberish | null
    ): NewValueSetEventFilter;
    NewValueSet(_value?: BigNumberish | null): NewValueSetEventFilter;
  };

  estimateGas: {
    set(
      _value: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    get(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    set(
      _value: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    get(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
