/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import { UnsignedTransaction } from "ethers/utils/transaction";
import { TypedEventDescription, TypedFunctionDescription } from ".";

interface EthereumGatewayV2Interface extends Interface {
  functions: {
    vmc: TypedFunctionDescription<{ encode([]: []): string }>;

    getAllowAnyToken: TypedFunctionDescription<{ encode([]: []): string }>;

    loomAddress: TypedFunctionDescription<{ encode([]: []): string }>;

    depositERC20: TypedFunctionDescription<{
      encode([amount, contractAddress]: [BigNumberish, string]): string;
    }>;

    enableGateway: TypedFunctionDescription<{
      encode([enable]: [boolean]): string;
    }>;

    getERC20: TypedFunctionDescription<{
      encode([contractAddress]: [string]): string;
    }>;

    nonces: TypedFunctionDescription<{ encode([]: [string]): string }>;

    getOwner: TypedFunctionDescription<{ encode([]: []): string }>;

    owner: TypedFunctionDescription<{ encode([]: []): string }>;

    withdrawERC20: TypedFunctionDescription<{
      encode([amount, contractAddress, _signersIndexes, _v, _r, _s]: [
        BigNumberish,
        string,
        BigNumberish[],
        BigNumberish[],
        Arrayish[],
        Arrayish[]
      ]): string;
    }>;

    toggleAllowToken: TypedFunctionDescription<{
      encode([tokenAddress, allow]: [string, boolean]): string;
    }>;

    getGatewayEnabled: TypedFunctionDescription<{ encode([]: []): string }>;

    toggleAllowAnyToken: TypedFunctionDescription<{
      encode([allow]: [boolean]): string;
    }>;

    allowedTokens: TypedFunctionDescription<{ encode([]: [string]): string }>;

    isTokenAllowed: TypedFunctionDescription<{
      encode([tokenAddress]: [string]): string;
    }>;

    withdrawERC721X: TypedFunctionDescription<{
      encode([tokenId, amount, contractAddress, _signersIndexes, _v, _r, _s]: [
        BigNumberish,
        BigNumberish,
        string,
        BigNumberish[],
        BigNumberish[],
        Arrayish[],
        Arrayish[]
      ]): string;
    }>;

    withdrawERC721: TypedFunctionDescription<{
      encode([uid, contractAddress, _signersIndexes, _v, _r, _s]: [
        BigNumberish,
        string,
        BigNumberish[],
        BigNumberish[],
        Arrayish[],
        Arrayish[]
      ]): string;
    }>;

    withdrawETH: TypedFunctionDescription<{
      encode([amount, _signersIndexes, _v, _r, _s]: [
        BigNumberish,
        BigNumberish[],
        BigNumberish[],
        Arrayish[],
        Arrayish[]
      ]): string;
    }>;

    onERC721XReceived: TypedFunctionDescription<{
      encode([_operator, _from, _tokenId, _amount, _data]: [
        string,
        string,
        BigNumberish,
        BigNumberish,
        Arrayish
      ]): string;
    }>;

    onERC721XBatchReceived: TypedFunctionDescription<{
      encode([_operator, _from, _types, _amounts, _data]: [
        string,
        string,
        BigNumberish[],
        BigNumberish[],
        Arrayish
      ]): string;
    }>;

    onERC721Received: TypedFunctionDescription<{
      encode([_operator, _from, _uid, _data]: [
        string,
        string,
        BigNumberish,
        Arrayish
      ]): string;
    }>;

    getETH: TypedFunctionDescription<{ encode([]: []): string }>;

    getERC721: TypedFunctionDescription<{
      encode([uid, contractAddress]: [BigNumberish, string]): string;
    }>;

    getERC721X: TypedFunctionDescription<{
      encode([tokenId, contractAddress]: [BigNumberish, string]): string;
    }>;
  };

  events: {
    ETHReceived: TypedEventDescription<{
      encodeTopics([from, amount]: [null, null]): string[];
    }>;

    ERC721Received: TypedEventDescription<{
      encodeTopics([operator, from, tokenId, contractAddress, data]: [
        null,
        null,
        null,
        null,
        null
      ]): string[];
    }>;

    ERC721XReceived: TypedEventDescription<{
      encodeTopics([operator, from, tokenId, amount, contractAddress, data]: [
        null,
        null,
        null,
        null,
        null,
        null
      ]): string[];
    }>;

    ERC721XBatchReceived: TypedEventDescription<{
      encodeTopics([operator, to, tokenTypes, amounts, contractAddress, data]: [
        null,
        null,
        null,
        null,
        null,
        null
      ]): string[];
    }>;

    TokenWithdrawn: TypedEventDescription<{
      encodeTopics([owner, kind, contractAddress, value]: [
        string | null,
        null,
        null,
        null
      ]): string[];
    }>;

    LoomCoinReceived: TypedEventDescription<{
      encodeTopics([from, amount, loomCoinAddress]: [
        string | null,
        null,
        null
      ]): string[];
    }>;

    ERC20Received: TypedEventDescription<{
      encodeTopics([from, amount, contractAddress]: [
        null,
        null,
        null
      ]): string[];
    }>;
  };
}

export class EthereumGatewayV2 extends Contract {
  connect(signerOrProvider: Signer | Provider | string): EthereumGatewayV2;
  attach(addressOrName: string): EthereumGatewayV2;
  deployed(): Promise<EthereumGatewayV2>;

  on(event: EventFilter | string, listener: Listener): EthereumGatewayV2;
  once(event: EventFilter | string, listener: Listener): EthereumGatewayV2;
  addListener(
    eventName: EventFilter | string,
    listener: Listener
  ): EthereumGatewayV2;
  removeAllListeners(eventName: EventFilter | string): EthereumGatewayV2;
  removeListener(eventName: any, listener: Listener): EthereumGatewayV2;

  interface: EthereumGatewayV2Interface;

  functions: {
    vmc(overrides?: UnsignedTransaction): Promise<string>;

    "vmc()"(overrides?: UnsignedTransaction): Promise<string>;

    getAllowAnyToken(overrides?: UnsignedTransaction): Promise<boolean>;

    "getAllowAnyToken()"(overrides?: UnsignedTransaction): Promise<boolean>;

    loomAddress(overrides?: UnsignedTransaction): Promise<string>;

    "loomAddress()"(overrides?: UnsignedTransaction): Promise<string>;

    depositERC20(
      amount: BigNumberish,
      contractAddress: string,
      overrides?: UnsignedTransaction
    ): Promise<ContractTransaction>;

    "depositERC20(uint256,address)"(
      amount: BigNumberish,
      contractAddress: string,
      overrides?: UnsignedTransaction
    ): Promise<ContractTransaction>;

    enableGateway(
      enable: boolean,
      overrides?: UnsignedTransaction
    ): Promise<ContractTransaction>;

    "enableGateway(bool)"(
      enable: boolean,
      overrides?: UnsignedTransaction
    ): Promise<ContractTransaction>;

    getERC20(
      contractAddress: string,
      overrides?: UnsignedTransaction
    ): Promise<BigNumber>;

    "getERC20(address)"(
      contractAddress: string,
      overrides?: UnsignedTransaction
    ): Promise<BigNumber>;

    nonces(arg0: string, overrides?: UnsignedTransaction): Promise<BigNumber>;

    "nonces(address)"(
      arg0: string,
      overrides?: UnsignedTransaction
    ): Promise<BigNumber>;

    getOwner(overrides?: UnsignedTransaction): Promise<string>;

    "getOwner()"(overrides?: UnsignedTransaction): Promise<string>;

    owner(overrides?: UnsignedTransaction): Promise<string>;

    "owner()"(overrides?: UnsignedTransaction): Promise<string>;

    withdrawERC20(
      amount: BigNumberish,
      contractAddress: string,
      _signersIndexes: BigNumberish[],
      _v: BigNumberish[],
      _r: Arrayish[],
      _s: Arrayish[],
      overrides?: UnsignedTransaction
    ): Promise<ContractTransaction>;

    "withdrawERC20(uint256,address,uint256[],uint8[],bytes32[],bytes32[])"(
      amount: BigNumberish,
      contractAddress: string,
      _signersIndexes: BigNumberish[],
      _v: BigNumberish[],
      _r: Arrayish[],
      _s: Arrayish[],
      overrides?: UnsignedTransaction
    ): Promise<ContractTransaction>;

    toggleAllowToken(
      tokenAddress: string,
      allow: boolean,
      overrides?: UnsignedTransaction
    ): Promise<ContractTransaction>;

    "toggleAllowToken(address,bool)"(
      tokenAddress: string,
      allow: boolean,
      overrides?: UnsignedTransaction
    ): Promise<ContractTransaction>;

    getGatewayEnabled(overrides?: UnsignedTransaction): Promise<boolean>;

    "getGatewayEnabled()"(overrides?: UnsignedTransaction): Promise<boolean>;

    toggleAllowAnyToken(
      allow: boolean,
      overrides?: UnsignedTransaction
    ): Promise<ContractTransaction>;

    "toggleAllowAnyToken(bool)"(
      allow: boolean,
      overrides?: UnsignedTransaction
    ): Promise<ContractTransaction>;

    allowedTokens(
      arg0: string,
      overrides?: UnsignedTransaction
    ): Promise<boolean>;

    "allowedTokens(address)"(
      arg0: string,
      overrides?: UnsignedTransaction
    ): Promise<boolean>;

    isTokenAllowed(
      tokenAddress: string,
      overrides?: UnsignedTransaction
    ): Promise<boolean>;

    "isTokenAllowed(address)"(
      tokenAddress: string,
      overrides?: UnsignedTransaction
    ): Promise<boolean>;

    withdrawERC721X(
      tokenId: BigNumberish,
      amount: BigNumberish,
      contractAddress: string,
      _signersIndexes: BigNumberish[],
      _v: BigNumberish[],
      _r: Arrayish[],
      _s: Arrayish[],
      overrides?: UnsignedTransaction
    ): Promise<ContractTransaction>;

    "withdrawERC721X(uint256,uint256,address,uint256[],uint8[],bytes32[],bytes32[])"(
      tokenId: BigNumberish,
      amount: BigNumberish,
      contractAddress: string,
      _signersIndexes: BigNumberish[],
      _v: BigNumberish[],
      _r: Arrayish[],
      _s: Arrayish[],
      overrides?: UnsignedTransaction
    ): Promise<ContractTransaction>;

    withdrawERC721(
      uid: BigNumberish,
      contractAddress: string,
      _signersIndexes: BigNumberish[],
      _v: BigNumberish[],
      _r: Arrayish[],
      _s: Arrayish[],
      overrides?: UnsignedTransaction
    ): Promise<ContractTransaction>;

    "withdrawERC721(uint256,address,uint256[],uint8[],bytes32[],bytes32[])"(
      uid: BigNumberish,
      contractAddress: string,
      _signersIndexes: BigNumberish[],
      _v: BigNumberish[],
      _r: Arrayish[],
      _s: Arrayish[],
      overrides?: UnsignedTransaction
    ): Promise<ContractTransaction>;

    withdrawETH(
      amount: BigNumberish,
      _signersIndexes: BigNumberish[],
      _v: BigNumberish[],
      _r: Arrayish[],
      _s: Arrayish[],
      overrides?: UnsignedTransaction
    ): Promise<ContractTransaction>;

    "withdrawETH(uint256,uint256[],uint8[],bytes32[],bytes32[])"(
      amount: BigNumberish,
      _signersIndexes: BigNumberish[],
      _v: BigNumberish[],
      _r: Arrayish[],
      _s: Arrayish[],
      overrides?: UnsignedTransaction
    ): Promise<ContractTransaction>;

    onERC721XReceived(
      _operator: string,
      _from: string,
      _tokenId: BigNumberish,
      _amount: BigNumberish,
      _data: Arrayish,
      overrides?: UnsignedTransaction
    ): Promise<ContractTransaction>;

    "onERC721XReceived(address,address,uint256,uint256,bytes)"(
      _operator: string,
      _from: string,
      _tokenId: BigNumberish,
      _amount: BigNumberish,
      _data: Arrayish,
      overrides?: UnsignedTransaction
    ): Promise<ContractTransaction>;

    onERC721XBatchReceived(
      _operator: string,
      _from: string,
      _types: BigNumberish[],
      _amounts: BigNumberish[],
      _data: Arrayish,
      overrides?: UnsignedTransaction
    ): Promise<ContractTransaction>;

    "onERC721XBatchReceived(address,address,uint256[],uint256[],bytes)"(
      _operator: string,
      _from: string,
      _types: BigNumberish[],
      _amounts: BigNumberish[],
      _data: Arrayish,
      overrides?: UnsignedTransaction
    ): Promise<ContractTransaction>;

    onERC721Received(
      _operator: string,
      _from: string,
      _uid: BigNumberish,
      _data: Arrayish,
      overrides?: UnsignedTransaction
    ): Promise<ContractTransaction>;

    "onERC721Received(address,address,uint256,bytes)"(
      _operator: string,
      _from: string,
      _uid: BigNumberish,
      _data: Arrayish,
      overrides?: UnsignedTransaction
    ): Promise<ContractTransaction>;

    getETH(overrides?: UnsignedTransaction): Promise<BigNumber>;

    "getETH()"(overrides?: UnsignedTransaction): Promise<BigNumber>;

    getERC721(
      uid: BigNumberish,
      contractAddress: string,
      overrides?: UnsignedTransaction
    ): Promise<boolean>;

    "getERC721(uint256,address)"(
      uid: BigNumberish,
      contractAddress: string,
      overrides?: UnsignedTransaction
    ): Promise<boolean>;

    getERC721X(
      tokenId: BigNumberish,
      contractAddress: string,
      overrides?: UnsignedTransaction
    ): Promise<BigNumber>;

    "getERC721X(uint256,address)"(
      tokenId: BigNumberish,
      contractAddress: string,
      overrides?: UnsignedTransaction
    ): Promise<BigNumber>;
  };

  vmc(overrides?: UnsignedTransaction): Promise<string>;

  "vmc()"(overrides?: UnsignedTransaction): Promise<string>;

  getAllowAnyToken(overrides?: UnsignedTransaction): Promise<boolean>;

  "getAllowAnyToken()"(overrides?: UnsignedTransaction): Promise<boolean>;

  loomAddress(overrides?: UnsignedTransaction): Promise<string>;

  "loomAddress()"(overrides?: UnsignedTransaction): Promise<string>;

  depositERC20(
    amount: BigNumberish,
    contractAddress: string,
    overrides?: UnsignedTransaction
  ): Promise<ContractTransaction>;

  "depositERC20(uint256,address)"(
    amount: BigNumberish,
    contractAddress: string,
    overrides?: UnsignedTransaction
  ): Promise<ContractTransaction>;

  enableGateway(
    enable: boolean,
    overrides?: UnsignedTransaction
  ): Promise<ContractTransaction>;

  "enableGateway(bool)"(
    enable: boolean,
    overrides?: UnsignedTransaction
  ): Promise<ContractTransaction>;

  getERC20(
    contractAddress: string,
    overrides?: UnsignedTransaction
  ): Promise<BigNumber>;

  "getERC20(address)"(
    contractAddress: string,
    overrides?: UnsignedTransaction
  ): Promise<BigNumber>;

  nonces(arg0: string, overrides?: UnsignedTransaction): Promise<BigNumber>;

  "nonces(address)"(
    arg0: string,
    overrides?: UnsignedTransaction
  ): Promise<BigNumber>;

  getOwner(overrides?: UnsignedTransaction): Promise<string>;

  "getOwner()"(overrides?: UnsignedTransaction): Promise<string>;

  owner(overrides?: UnsignedTransaction): Promise<string>;

  "owner()"(overrides?: UnsignedTransaction): Promise<string>;

  withdrawERC20(
    amount: BigNumberish,
    contractAddress: string,
    _signersIndexes: BigNumberish[],
    _v: BigNumberish[],
    _r: Arrayish[],
    _s: Arrayish[],
    overrides?: UnsignedTransaction
  ): Promise<ContractTransaction>;

  "withdrawERC20(uint256,address,uint256[],uint8[],bytes32[],bytes32[])"(
    amount: BigNumberish,
    contractAddress: string,
    _signersIndexes: BigNumberish[],
    _v: BigNumberish[],
    _r: Arrayish[],
    _s: Arrayish[],
    overrides?: UnsignedTransaction
  ): Promise<ContractTransaction>;

  toggleAllowToken(
    tokenAddress: string,
    allow: boolean,
    overrides?: UnsignedTransaction
  ): Promise<ContractTransaction>;

  "toggleAllowToken(address,bool)"(
    tokenAddress: string,
    allow: boolean,
    overrides?: UnsignedTransaction
  ): Promise<ContractTransaction>;

  getGatewayEnabled(overrides?: UnsignedTransaction): Promise<boolean>;

  "getGatewayEnabled()"(overrides?: UnsignedTransaction): Promise<boolean>;

  toggleAllowAnyToken(
    allow: boolean,
    overrides?: UnsignedTransaction
  ): Promise<ContractTransaction>;

  "toggleAllowAnyToken(bool)"(
    allow: boolean,
    overrides?: UnsignedTransaction
  ): Promise<ContractTransaction>;

  allowedTokens(
    arg0: string,
    overrides?: UnsignedTransaction
  ): Promise<boolean>;

  "allowedTokens(address)"(
    arg0: string,
    overrides?: UnsignedTransaction
  ): Promise<boolean>;

  isTokenAllowed(
    tokenAddress: string,
    overrides?: UnsignedTransaction
  ): Promise<boolean>;

  "isTokenAllowed(address)"(
    tokenAddress: string,
    overrides?: UnsignedTransaction
  ): Promise<boolean>;

  withdrawERC721X(
    tokenId: BigNumberish,
    amount: BigNumberish,
    contractAddress: string,
    _signersIndexes: BigNumberish[],
    _v: BigNumberish[],
    _r: Arrayish[],
    _s: Arrayish[],
    overrides?: UnsignedTransaction
  ): Promise<ContractTransaction>;

  "withdrawERC721X(uint256,uint256,address,uint256[],uint8[],bytes32[],bytes32[])"(
    tokenId: BigNumberish,
    amount: BigNumberish,
    contractAddress: string,
    _signersIndexes: BigNumberish[],
    _v: BigNumberish[],
    _r: Arrayish[],
    _s: Arrayish[],
    overrides?: UnsignedTransaction
  ): Promise<ContractTransaction>;

  withdrawERC721(
    uid: BigNumberish,
    contractAddress: string,
    _signersIndexes: BigNumberish[],
    _v: BigNumberish[],
    _r: Arrayish[],
    _s: Arrayish[],
    overrides?: UnsignedTransaction
  ): Promise<ContractTransaction>;

  "withdrawERC721(uint256,address,uint256[],uint8[],bytes32[],bytes32[])"(
    uid: BigNumberish,
    contractAddress: string,
    _signersIndexes: BigNumberish[],
    _v: BigNumberish[],
    _r: Arrayish[],
    _s: Arrayish[],
    overrides?: UnsignedTransaction
  ): Promise<ContractTransaction>;

  withdrawETH(
    amount: BigNumberish,
    _signersIndexes: BigNumberish[],
    _v: BigNumberish[],
    _r: Arrayish[],
    _s: Arrayish[],
    overrides?: UnsignedTransaction
  ): Promise<ContractTransaction>;

  "withdrawETH(uint256,uint256[],uint8[],bytes32[],bytes32[])"(
    amount: BigNumberish,
    _signersIndexes: BigNumberish[],
    _v: BigNumberish[],
    _r: Arrayish[],
    _s: Arrayish[],
    overrides?: UnsignedTransaction
  ): Promise<ContractTransaction>;

  onERC721XReceived(
    _operator: string,
    _from: string,
    _tokenId: BigNumberish,
    _amount: BigNumberish,
    _data: Arrayish,
    overrides?: UnsignedTransaction
  ): Promise<ContractTransaction>;

  "onERC721XReceived(address,address,uint256,uint256,bytes)"(
    _operator: string,
    _from: string,
    _tokenId: BigNumberish,
    _amount: BigNumberish,
    _data: Arrayish,
    overrides?: UnsignedTransaction
  ): Promise<ContractTransaction>;

  onERC721XBatchReceived(
    _operator: string,
    _from: string,
    _types: BigNumberish[],
    _amounts: BigNumberish[],
    _data: Arrayish,
    overrides?: UnsignedTransaction
  ): Promise<ContractTransaction>;

  "onERC721XBatchReceived(address,address,uint256[],uint256[],bytes)"(
    _operator: string,
    _from: string,
    _types: BigNumberish[],
    _amounts: BigNumberish[],
    _data: Arrayish,
    overrides?: UnsignedTransaction
  ): Promise<ContractTransaction>;

  onERC721Received(
    _operator: string,
    _from: string,
    _uid: BigNumberish,
    _data: Arrayish,
    overrides?: UnsignedTransaction
  ): Promise<ContractTransaction>;

  "onERC721Received(address,address,uint256,bytes)"(
    _operator: string,
    _from: string,
    _uid: BigNumberish,
    _data: Arrayish,
    overrides?: UnsignedTransaction
  ): Promise<ContractTransaction>;

  getETH(overrides?: UnsignedTransaction): Promise<BigNumber>;

  "getETH()"(overrides?: UnsignedTransaction): Promise<BigNumber>;

  getERC721(
    uid: BigNumberish,
    contractAddress: string,
    overrides?: UnsignedTransaction
  ): Promise<boolean>;

  "getERC721(uint256,address)"(
    uid: BigNumberish,
    contractAddress: string,
    overrides?: UnsignedTransaction
  ): Promise<boolean>;

  getERC721X(
    tokenId: BigNumberish,
    contractAddress: string,
    overrides?: UnsignedTransaction
  ): Promise<BigNumber>;

  "getERC721X(uint256,address)"(
    tokenId: BigNumberish,
    contractAddress: string,
    overrides?: UnsignedTransaction
  ): Promise<BigNumber>;

  filters: {
    ETHReceived(from: null, amount: null): EventFilter;

    ERC721Received(
      operator: null,
      from: null,
      tokenId: null,
      contractAddress: null,
      data: null
    ): EventFilter;

    ERC721XReceived(
      operator: null,
      from: null,
      tokenId: null,
      amount: null,
      contractAddress: null,
      data: null
    ): EventFilter;

    ERC721XBatchReceived(
      operator: null,
      to: null,
      tokenTypes: null,
      amounts: null,
      contractAddress: null,
      data: null
    ): EventFilter;

    TokenWithdrawn(
      owner: string | null,
      kind: null,
      contractAddress: null,
      value: null
    ): EventFilter;

    LoomCoinReceived(
      from: string | null,
      amount: null,
      loomCoinAddress: null
    ): EventFilter;

    ERC20Received(from: null, amount: null, contractAddress: null): EventFilter;
  };

  estimate: {
    vmc(overrides?: UnsignedTransaction): Promise<BigNumber>;

    "vmc()"(overrides?: UnsignedTransaction): Promise<BigNumber>;

    getAllowAnyToken(overrides?: UnsignedTransaction): Promise<BigNumber>;

    "getAllowAnyToken()"(overrides?: UnsignedTransaction): Promise<BigNumber>;

    loomAddress(overrides?: UnsignedTransaction): Promise<BigNumber>;

    "loomAddress()"(overrides?: UnsignedTransaction): Promise<BigNumber>;

    depositERC20(
      amount: BigNumberish,
      contractAddress: string,
      overrides?: UnsignedTransaction
    ): Promise<BigNumber>;

    "depositERC20(uint256,address)"(
      amount: BigNumberish,
      contractAddress: string,
      overrides?: UnsignedTransaction
    ): Promise<BigNumber>;

    enableGateway(
      enable: boolean,
      overrides?: UnsignedTransaction
    ): Promise<BigNumber>;

    "enableGateway(bool)"(
      enable: boolean,
      overrides?: UnsignedTransaction
    ): Promise<BigNumber>;

    getERC20(
      contractAddress: string,
      overrides?: UnsignedTransaction
    ): Promise<BigNumber>;

    "getERC20(address)"(
      contractAddress: string,
      overrides?: UnsignedTransaction
    ): Promise<BigNumber>;

    nonces(arg0: string, overrides?: UnsignedTransaction): Promise<BigNumber>;

    "nonces(address)"(
      arg0: string,
      overrides?: UnsignedTransaction
    ): Promise<BigNumber>;

    getOwner(overrides?: UnsignedTransaction): Promise<BigNumber>;

    "getOwner()"(overrides?: UnsignedTransaction): Promise<BigNumber>;

    owner(overrides?: UnsignedTransaction): Promise<BigNumber>;

    "owner()"(overrides?: UnsignedTransaction): Promise<BigNumber>;

    withdrawERC20(
      amount: BigNumberish,
      contractAddress: string,
      _signersIndexes: BigNumberish[],
      _v: BigNumberish[],
      _r: Arrayish[],
      _s: Arrayish[],
      overrides?: UnsignedTransaction
    ): Promise<BigNumber>;

    "withdrawERC20(uint256,address,uint256[],uint8[],bytes32[],bytes32[])"(
      amount: BigNumberish,
      contractAddress: string,
      _signersIndexes: BigNumberish[],
      _v: BigNumberish[],
      _r: Arrayish[],
      _s: Arrayish[],
      overrides?: UnsignedTransaction
    ): Promise<BigNumber>;

    toggleAllowToken(
      tokenAddress: string,
      allow: boolean,
      overrides?: UnsignedTransaction
    ): Promise<BigNumber>;

    "toggleAllowToken(address,bool)"(
      tokenAddress: string,
      allow: boolean,
      overrides?: UnsignedTransaction
    ): Promise<BigNumber>;

    getGatewayEnabled(overrides?: UnsignedTransaction): Promise<BigNumber>;

    "getGatewayEnabled()"(overrides?: UnsignedTransaction): Promise<BigNumber>;

    toggleAllowAnyToken(
      allow: boolean,
      overrides?: UnsignedTransaction
    ): Promise<BigNumber>;

    "toggleAllowAnyToken(bool)"(
      allow: boolean,
      overrides?: UnsignedTransaction
    ): Promise<BigNumber>;

    allowedTokens(
      arg0: string,
      overrides?: UnsignedTransaction
    ): Promise<BigNumber>;

    "allowedTokens(address)"(
      arg0: string,
      overrides?: UnsignedTransaction
    ): Promise<BigNumber>;

    isTokenAllowed(
      tokenAddress: string,
      overrides?: UnsignedTransaction
    ): Promise<BigNumber>;

    "isTokenAllowed(address)"(
      tokenAddress: string,
      overrides?: UnsignedTransaction
    ): Promise<BigNumber>;

    withdrawERC721X(
      tokenId: BigNumberish,
      amount: BigNumberish,
      contractAddress: string,
      _signersIndexes: BigNumberish[],
      _v: BigNumberish[],
      _r: Arrayish[],
      _s: Arrayish[],
      overrides?: UnsignedTransaction
    ): Promise<BigNumber>;

    "withdrawERC721X(uint256,uint256,address,uint256[],uint8[],bytes32[],bytes32[])"(
      tokenId: BigNumberish,
      amount: BigNumberish,
      contractAddress: string,
      _signersIndexes: BigNumberish[],
      _v: BigNumberish[],
      _r: Arrayish[],
      _s: Arrayish[],
      overrides?: UnsignedTransaction
    ): Promise<BigNumber>;

    withdrawERC721(
      uid: BigNumberish,
      contractAddress: string,
      _signersIndexes: BigNumberish[],
      _v: BigNumberish[],
      _r: Arrayish[],
      _s: Arrayish[],
      overrides?: UnsignedTransaction
    ): Promise<BigNumber>;

    "withdrawERC721(uint256,address,uint256[],uint8[],bytes32[],bytes32[])"(
      uid: BigNumberish,
      contractAddress: string,
      _signersIndexes: BigNumberish[],
      _v: BigNumberish[],
      _r: Arrayish[],
      _s: Arrayish[],
      overrides?: UnsignedTransaction
    ): Promise<BigNumber>;

    withdrawETH(
      amount: BigNumberish,
      _signersIndexes: BigNumberish[],
      _v: BigNumberish[],
      _r: Arrayish[],
      _s: Arrayish[],
      overrides?: UnsignedTransaction
    ): Promise<BigNumber>;

    "withdrawETH(uint256,uint256[],uint8[],bytes32[],bytes32[])"(
      amount: BigNumberish,
      _signersIndexes: BigNumberish[],
      _v: BigNumberish[],
      _r: Arrayish[],
      _s: Arrayish[],
      overrides?: UnsignedTransaction
    ): Promise<BigNumber>;

    onERC721XReceived(
      _operator: string,
      _from: string,
      _tokenId: BigNumberish,
      _amount: BigNumberish,
      _data: Arrayish,
      overrides?: UnsignedTransaction
    ): Promise<BigNumber>;

    "onERC721XReceived(address,address,uint256,uint256,bytes)"(
      _operator: string,
      _from: string,
      _tokenId: BigNumberish,
      _amount: BigNumberish,
      _data: Arrayish,
      overrides?: UnsignedTransaction
    ): Promise<BigNumber>;

    onERC721XBatchReceived(
      _operator: string,
      _from: string,
      _types: BigNumberish[],
      _amounts: BigNumberish[],
      _data: Arrayish,
      overrides?: UnsignedTransaction
    ): Promise<BigNumber>;

    "onERC721XBatchReceived(address,address,uint256[],uint256[],bytes)"(
      _operator: string,
      _from: string,
      _types: BigNumberish[],
      _amounts: BigNumberish[],
      _data: Arrayish,
      overrides?: UnsignedTransaction
    ): Promise<BigNumber>;

    onERC721Received(
      _operator: string,
      _from: string,
      _uid: BigNumberish,
      _data: Arrayish,
      overrides?: UnsignedTransaction
    ): Promise<BigNumber>;

    "onERC721Received(address,address,uint256,bytes)"(
      _operator: string,
      _from: string,
      _uid: BigNumberish,
      _data: Arrayish,
      overrides?: UnsignedTransaction
    ): Promise<BigNumber>;

    getETH(overrides?: UnsignedTransaction): Promise<BigNumber>;

    "getETH()"(overrides?: UnsignedTransaction): Promise<BigNumber>;

    getERC721(
      uid: BigNumberish,
      contractAddress: string,
      overrides?: UnsignedTransaction
    ): Promise<BigNumber>;

    "getERC721(uint256,address)"(
      uid: BigNumberish,
      contractAddress: string,
      overrides?: UnsignedTransaction
    ): Promise<BigNumber>;

    getERC721X(
      tokenId: BigNumberish,
      contractAddress: string,
      overrides?: UnsignedTransaction
    ): Promise<BigNumber>;

    "getERC721X(uint256,address)"(
      tokenId: BigNumberish,
      contractAddress: string,
      overrides?: UnsignedTransaction
    ): Promise<BigNumber>;
  };
}
