name: CI

on:
  push:
    branches: [ci-test]
  pull_request:
    branches: [ci-test]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: "1.10.2"
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: "11.x"

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache yarn cache
        uses: actions/cache@v2
        id: cache-yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ matrix.node-version }}-nodemodules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node-version }}-nodemodules-

      - name: setup protoc3
        run: ./.travis_before_install.sh
      - name: Install xvfb for browser tests
        run: apt-get install xvfb
      - run: chmod +x ./e2e_tests.sh
      - run: yarn install
      # - run: yarn test
      - run: ./.travis_e2e_test.sh
