name: CI

on:
  push:
    branches: [ci-test]
  pull_request:
    branches: [master, ci-test]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      # - uses: actions/setup-go@v2
      #   with:
      #     go-version: "1.10.2"
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: "11.x"

      - name: install
        uses: actions/install

      # - name: Cache Go modules
      #   uses: actions/cache@preview
      #   with:
      #     path: ~/go/pkg/mod
      #     key: ${{ runner.os }}-build-${{ hashFiles('**/go.sum') }}
      #     restore-keys: |
      #       ${{ runner.OS }}-build-${{ env.cache-name }}-
      #       ${{ runner.OS }}-build-
      #       ${{ runner.OS }}-

      - name: Setup protoc3
        run: ./scripts/ci_install_protoc3.sh
      # - name: Install xvfb for browser tests
      #   run: sudo apt-get install xvfb
      - run: chmod +x ./e2e_tests.sh
      - run: yarn install
      - run: xvfb-run --auto-servernum yarn test:browser
        # env:
        #    DISPLAY: ":99"
      # - run: ./scripts/ci_e2e_test.sh
      #   working-directory: "."
