name: CI

on:
  push:
    branches: [ci-test]
  pull_request:
    branches: [master, ci-test]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: "11.x"
      - uses: actions/setup-go@v2
        with:
          go-version: "1.10.2"

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache yarn cache
        uses: actions/cache@v2
        id: cache-yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ matrix.node-version }}-nodemodules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node-version }}-nodemodules-

      # - name: Cache Go modules
      #   uses: actions/cache@preview
      #   with:
      #     path: ~/go/pkg/mod
      #     key: ${{ runner.os }}-build-${{ hashFiles('**/go.sum') }}
      #     restore-keys: |
      #       ${{ runner.OS }}-build-${{ env.cache-name }}-
      #       ${{ runner.OS }}-build-
      #       ${{ runner.OS }}-

      - run: yarn install
      - run: xvfb-run --auto-servernum yarn test:browser
      # - run: yarn test:node
      # # e2e test
      # - name: Setup protoc3
      #   run: ./scripts/ci_install_protoc3.sh
      # - run: chmod +x ./e2e_tests.sh
      # - run: ./scripts/ci_e2e_test.sh
      #   working-directory: "."
